data_ingestion:
  bucket_name : "trip-data"
  object_name : "fhv_tripdata.parquet"
  storage_path : "s3.ir-thr-at1.arvanstorage.ir"
  extra_part: "X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=254f0b27-805a-4da4-af26-d746c6a3a15e%2F20250508%2Fir-thr-at1%2Fs3%2Faws4_request&X-Amz-Date=20250508T113315Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&versionId=&X-Amz-Signature=950a6cde1e58cae93a72071ffd5e53295539aeeb6173234024c6115f774470d4"
  artfact_dir: artifacts

data_processing:
  shift: 18
  val_test_ratio: 0.3
  test_ratio: 0.5

traning_model:
  selected_model: 'random_forest'
  
  models_to_run:
  - name: random_forest
    params:
        n_estimators: 300
        max_samples: 0.9
        n_jobs: -1

  - name: gradient_boosting
    params:
        n_estimators: 300
        max_samples: 0.9
        n_jobs: -1
 
web:
  host: "0.0.0.0"
  port: 8080
  model_output_dir: "artifacts/models"
  model_name: "rf.joblib"
